### ISSUE TITLE
Import multiple resource groups into one state file.

### ISSUE THREAD

**Issue by Akky8055** [Azure/aztfexport#249]
Is there any way to import multiple resource groups in one single state.

I tried to --append command but fails.

I ran below commands on single empty dir. Sorry I'm new to this.
Aztfy rg "rg name1"
aztfy --append rg "rg name2"

Error: flag provided but not defined: -append

Error:

**Comment by stemaMSFT** [comment]
Hi @Akky8055 try `aztfy rg —append`:)

**Comment by magodo** [comment]
@Akky8055 Instead of running the `rg` subcommand with `--append` multiple times, you can try the `query` subcommand to query multiple resource groups under a subscription.

Since we haven't get further response from you, I'll mark this issue as closed for now. Feel free to reopen it if the issue still remains.
