### ISSUE TITLE
Using custom resource names

### ISSUE THREAD

**Issue by yashvit** [Azure/aztfexport#258]
Would be nice to have some documentation to show how we can use custom resource names instead of res-0, res-1, etc. 

Maybe the default resource names are taken based on the actual name of the azure resource?

I am trying to save the resources to a mapping file, modify the names as I want and then import based on the mapping file. Is this the best way to do it?

**Comment by magodo** [comment]
@yashvit Yes, modifying the names from the mapping file is the expected approach for now. 

Alternatively, if the resource list is not that long, you can also do it from the interactive terminal UI. Furthermore, if you are on `resource` mode, you can specify the `--name` to set another name rather than `res-0`; Similarly, in `rg`/`query` mode, you can use `--name-pattern` to set a different name pattern rather than `res-*`.

It might be tempting to provide some syntax to allow users to customize the name pattern, e.g. using `${name}` to use the resource name as its TF address label. However, some resource name might not be a valid TF address label (e.g. has empty space in it).

**Comment by magodo** [comment]
@yashvit Since we haven't get further response from you, I'll mark this issue as closed for now. Feel free to reopen it if the issue still remains.
