### ISSUE TITLE
Resources with Space in the name generate bad TF

### ISSUE THREAD

**Issue by emilwester-optimizely** [Azure/aztfexport#259]
Some resources in azure have space in them. This generates bad TF and errors when doing terraform apply

TF code:
```
resource "azurerm_monitor_smart_detector_alert_rule" "res-486" {
  description         = "Failure Anomalies notifies you of an unusual rise in the rate of failed HTTP requests or dependency calls."
  detector_type       = "FailureAnomaliesDetector"
  frequency           = "PT1M"
  name                = "Failure Anomalies - REMOVED"
  resource_group_name = "REMOVED"
  scope_resource_ids  = ["/subscriptions/REMOVED/resourcegroups/REMOVED/providers/microsoft.insights/components/REMOVED"]
  severity            = "Sev3"
  action_group {
    ids = ["/subscriptions/REMOVED/resourcegroups/REMOVED/providers/microsoft.insights/actiongroups/application insights smart detection"]
  }
  depends_on = [
    azurerm_resource_group.res-0,
  ]
}

```

TF apply response:
```
Error: ID was missing the `actionGroups` element
│ 
│   with azurerm_monitor_smart_detector_alert_rule.res-486,
│   on main.tf line 837, in resource "azurerm_monitor_smart_detector_alert_rule" "res-486":
│  837:     ids = ["/subscriptions/REMOVED/resourcegroups/REMOVED/providers/microsoft.insights/actiongroups/application insights smart detection"]
```

I have tried replacing the space with + and %20 but it still fails.

this is related to: 
[https://github.com/Azure/azure-cli/issues/12885](https://github.com/Azure/azure-cli/issues/12885)
but there is a workaround in comment: 
[https://github.com/Azure/azure-cli/issues/12885#issuecomment-620561833](https://github.com/Azure/azure-cli/issues/12885#issuecomment-620561833)

Can we implement a similar workaround until fixed?

**Comment by magodo** [comment]
@emilwester-optimizely Thank you for submitting this! The issue is not caused by the empty space in the resource name, but the casing of the element in the `ids` array. The only change needed to make this work is to modify the `actiongroups` to `actionGroups`.

The reason why this happens is because the provider has some special handling for this property: https://github.com/hashicorp/terraform-provider-azurerm/blob/04eaea00a40d28f447c55e084ef1aef47139d1b0/internal/services/monitor/monitor_smart_detector_alert_rule_resource.go#L108. This makes all the characters to be lowercased. However, when the provider read this in, it requires it to be case sensitive, which result into the error you saw.

Currently, `aztfy` doesn't tune these property-level issues, for the sake of maintainability.

**Comment by harshitjain5june** [comment]
any update on this issue? as I still faced this same issue while using `aztfexport`

**Comment by magodo** [comment]
@harshitjain5june Upstream PR submitted to fix this issue.
