### ISSUE TITLE
Files into storage are also listed in state file

### ISSUE THREAD

**Issue by farreciado** [Azure/aztfexport#274]
Hello, I ran the tool to get a RG (running in production) resources file, and got like 3000 entries. As there actually were like 20-30 resources in that RG...I checked what happened and found thousands of media files (such mp4) present in an storage. Is there a way to avoid listing the resources inside an storage? Are the files inside storage considered resources? Thanks for helping and congrats for the tool.  <QUESTION> BTW process took really long, I wish with paralellism the execution time lowers!

**Comment by magodo** [comment]
@farreciado Assuming you are seeing thousands of `azurerm_storage_blob`, then yes they are also counted as valid resoruces in the RG. If you don't want to export them, you can modify the resource mapping file (named `aztfyResourceMapping.json`) to remove those entries and then run `aztfy map [options] <path2mappingFile>`.

The parallel import feature is implemeneted in #260 and will be available in the next release.

**Comment by magodo** [comment]
@farreciado That is because `aztfy` firstly recursively list all the Azure resources in the RG you've specified, where these assets are also listed. Then it maps these resources to the TF resource via its Azure resource id, and deduce the correct TF resource type, in this case it is `azurerm_media_asset`.

If you simply want to ignore the `azurerm_media_asset` resources, you can run following `jq` command:

```
cat aztfyResourceMapping.json | jq 'with_entries(select(.value.resource_type != "azurerm_media_asset"))'
```

**Comment by magodo** [comment]
@farreciado Since we haven't get further response from you, I'll mark this issue as closed for now. Feel free to reopen it if the issue still remains.
