### ISSUE TITLE
2 queries

### ISSUE THREAD

**Issue by ChaturvediSwati** [Azure/aztfexport#480]
Is there a way to specify the installed providers, so that each time it does not tries to download it ? And also is there a way to run 
below command in verbose mode.

aztfexport resource-group TestRg

**Comment by magodo** [comment]
Hi @ChaturvediSwati,

Ans 1: You can setup the [`plugin_cache_dir`](https://developer.hashicorp.com/terraform/cli/config/config-file#plugin_cache_dir) so that terraform will only download the provider once. There is also a hidden option `--tfclient-plugin-path` which can be used to specify the provider manually, but it only works when combined with `--hcl-only`.

Ans 2: You can use `--log-path=<file to record the log>` and `--log-level=TRACE`

**Comment by ChaturvediSwati** [comment]
Thanks for answering, could you please share any snippet or any document if that's available ? Here, as I am new to this, and still learning

**Comment by magodo** [comment]
Everthing you needed is documented here: https://developer.hashicorp.com/terraform/cli/config/config-file#plugin_cache_dir

**Comment by magodo** [comment]
:wave:

Since we've not heard back here I'm going to close this issue for the moment. Feel free to reopen if still have questions.
