### ISSUE TITLE
Exporting Azure API Management service exports bare minimum

### ISSUE THREAD

**Issue by Radamonas** [Azure/aztfexport#494]
I tried to export one resource only or whole resource group, however I was not able to get a lot from already existing APIM setup we have in the cloud:

```
resource "azurerm_api_management" "res-0" {
  location            = "westeurope"
  name                = "name"
  publisher_email     = "email@email.com"
  publisher_name      = "ACME"
  resource_group_name = "rg-acme"
  sku_name            = "Developer_1"

  identity {
    type = "SystemAssigned"
  }
}
```

I was interested to get ```hostname_configuration``` at least, but this information was not extracted even when I was running whole resource group extract.

**Comment by magodo** [comment]
Hi @Radamonas, by default the tool will ignore "zero" values or O(ptional)+C(omputed) properties, since the [goal](https://github.com/Azure/aztfexport#goal) of aztfexport is to generate valid configuration and pass terraform plan, otherwise, they might introduce other issues. If you really wants all the non-readonly properties to be exported, you can specify `--full-properties` flag.

**Comment by magodo** [comment]
:wave:

Since we've not heard back here I'm going to close this issue for the moment. Feel free to reopen if still have questions.
