### ISSUE TITLE
Not secure by default.

### ISSUE THREAD

**Issue by TimLovellSmith** [Azure/aztfexport#570]
#551 supplies a 'fix' for aztfexport leaking secure credentials, but it is the wrong fix, because it codifies the default as using the unmasked, insecure setting, i.e. is not secure by default:.

It should be secure by default, and require explicit steps to get the unmasked credentials in the template.

Tim

**Comment by magodo** [comment]
@TimLovellSmith This isn't a fix, but an option, which is only supposed to be used in some rare cases, esp. when this module is used as a library for other project that is security sensitive. Back to this `aztfexport` CLI tool itself, it streamlines the jobs for the resource discovery, import and configuration generation processes. During the resource import, reading all the resource attributes, including the credentials are codified in the provider itself, in this case it is https://github.com/hashicorp/terraform-provider-azurerm. There isn't really a way for TF to do multi-step import to add one more layer of barrier for security, which is also pointless for the CLI use case.

I'd appreciate you bring this topic here, whilst since it is out of the scope of this tool, I'm gonna close this issue for now.

**Comment by TimLovellSmith** [comment]
@magodo You're bringing up a reason that I don't yet fully understand, that reading all the resource attributes, including credentials, are codified in the provider itself. But it sounds like you're effectively saying 'the root of the problem lies elsewhere' - so should TF be charged with creating a way for TF to do multi-step import?

Presuming that the CLI use case has no interest in security is what I'd call "the enabling insecurity" point of view, where you're relying on the world not to make mistakes -- and thereby actually enabling them to make them.

**Comment by stemaMSFT** [comment]
@magodo I think what is being said here makes sense. How much information loss occurs if we don't mask by default?
